const nodemailer = require('nodemailer');

const allAction = (req,res,next) => {
    res.statusCode = 200;
    res.setHeader('Content-Type', 'application/json');
    next();
}

const sendEmail = async (req, res, next) => {
    try {
        const adminUsers = await models.User.findAll({
            where: {
                admin: 1
            },
            attributes: ['username']
        });
        if(adminUsers.length != 0) {
            let recipients = adminUsers.reduce((a,c) => {
                return a + ',' + c.dataValues.username;
            }, '');
            recipients = recipients.slice(1);

            let transporter = nodemailer.createTransport({
              service: 'gmail',
              auth: {
                user: process.env.MAIL_USERNAME,
                pass: process.env.MAIL_PASSWORD
              }
            });

            let mailOptions = {
              from: process.env.MAIL_USERNAME,
              to: recipients,
              subject: 'Confusion Customer Feedback',
              text: `
                Dear Admin,
                
                You have received the following feedback from a customer.
                
                ${JSON.stringify(req.body)}

                This email is auto-generated by Confusion Server.
              `
            };
            transporter.sendMail(mailOptions, (err, data) => {
              if (err) {
                res.statusCode = 500;
                res.json({});
              } else {
                res.json({...req.body});
              }
            });
        }
        else {
            console.log("No admin users to send the feedback to.");
            res.json({...req.body});
        }
    }
    catch(error) {
        next(error);
    }
}


module.exports = {
    allAction,
    sendEmail
}